Host: 0.0.0.0
Listen: 8081
ListenTLS: -1
RedirectHTTP: false
Backends:
  - Addr: localhost:3000
    Path: /ui
CertificateFile: /home/kenneth/Certs/butler.crt
CertificateKeyFile: /home/kenneth/Certs/butler.key
Registrar: false
RegistrarListen: 7070
